#!/bin/bash



Rscript -e "devtools::install_github(c(
  'SantanderMetGroup/loadeR.java',
  'SantanderMetGroup/climate4R.UDG',
  'SantanderMetGroup/loadeR',
  'SantanderMetGroup/transformeR',
  'SantanderMetGroup/visualizeR',
  'SantanderMetGroup/downscaleR'
))"

Rscript -e "IRkernel::installspec(user = FALSE)"
